server:
  port: 8081
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/myfirstapp
    password: Phani@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        type: debug
    hibernate:
      ddl-auto: update
    show-sql: 'true'
