server:
  port: 8081
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/myfirstapp
    password: Phani@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
